### ISSUE TITLE
使用RULF构建url crate时报错

### ISSUE THREAD

**Issue by q871795224** [Artisan-Lab/RULF#1]
在按照readme使用RULF对url crate进行目标构建时，报了如下的错误信息。
命令:
`fuzz-target-generator --edition=2018 --crate-type lib --crate-name url url/src/lib.rs -o /mnt/d/code/rulf_target/rust-url-2.2.0/target/doc --error-format=human -L dependency=/mnt/d/code/rulf_target/rust-url-2.2.0/target/debug/deps --extern form_urlencoded=/mnt/d/code/rulf_target/rust-url-2.2.0/target/debug/deps/libform_urlencoded-bc7e4e3edec2288c.rmeta --extern idna=/mnt/d/code/rulf_target/rust-url-2.2.0/target/debug/deps/libidna-af1d798f487b6dd1.rmeta --extern matches=/mnt/d/code/rulf_target/rust-url-2.2.0/target/debug/deps/libmatches-d43e56146936ddab.rmeta --extern percent_encoding=/mnt/d/code/rulf_target/rust-url-2.2.0/target/debug/deps/libpercent_encoding-d350808cca3b79c5.rmeta
`
错误信息：
![image](https://user-images.githubusercontent.com/33190881/149507312-0c4157de-83d5-4ed6-90fb-f71ceeb7d531.png)

请问该如何解决这一问题？

**Comment by q871795224** [comment]
请问 rustc 1.46.0-dev 版本应该去哪里获取？

**Comment by StevenJiang1110** [comment]
你好，我们当前的这个仓库就包括了1.46.0-dev版本的编译器的源码。在你编译完这个项目后，就能够在你的build目录下找到1.46.0-dev版本的rustc（当然，我们不会直接使用rustc，而是通过cargo来调用）。然后，你需要用rustup将你的编译器切换到1.46.0-dev版本。命令大概是
```shell
rustup toolchain link stage2 ${FUZZ_TARGET_GENERATOR_DIR}/build/x86*/stage2 && rustup default stage2 
```
其中FUZZ_TARGET_GENERATOR_DIR就是我们当前仓库所在的目录。此外，还需要设置PATH环境变量来将1.46.0-dev版本的cargo设置为默认的cargo。

另外，我们最近更新了我们的docker文件以及相应的脚本文件。我们推荐采用docker来构建环境并且进行实验，这是目前最简单的构建方法。可以参考我们的README中`How to use our tool with Docker`一节。

**Comment by hxuhack** [comment]
The problem should have been solved by the user.

**Comment by hxuhack** [comment]
The problem should have been solved by the user.

**Comment by hxuhack** [comment]
The problem should have been solved by the user.
