### ISSUE TITLE
请问RULF是否打算支持更高版本的rust？何时支持？

### ISSUE THREAD

**Issue by q871795224** [Artisan-Lab/RULF#2]
在使用RULF的过程，我发现有些crate依赖的rustc版本较新，故无法成功使用RULF。RULF打算对这样的crate做怎样的处理？RULF有支持更高版本rustc的计划吗？

**Comment by StevenJiang1110** [comment]
你好，我们最近也遇到了类似的问题，主要是很多新版本的库采用了edition 2021, 而RULF基于的编译器版本只能支持到edition 2018，最近我们也尝试性的做了一些迁移的工作希望移到1.60+版本的编译器上，但是编译器版本跨度太大，内部的数据结构变化较多，需要修改的代码也很多，我们目前主要的精力还是在支持泛型特性上，迁移到新版本编译器的优先级还比较低，短期内可能不会支持。

目前我们在实验中，如果遇到较新的无法支持的库，可能采取的方式有两种。一是测试一个可以支持的老版本，二是下载该库的源码，然后修改部分依赖库的版本到较老的版本

**Comment by hxuhack** [comment]
版本兼容性问题目前无法fix，计划在下一个主版更新支持。
