### ISSUE TITLE
Cannot compile in correct Rust version using docker

### ISSUE THREAD

**Issue by EricLiChH** [Artisan-Lab/RULF#5]
Hello, thank you for your work on Rust Fuzzing. When I used the `build-in-docker` script from the `develop` branch, I noticed that the Rust version downloaded is `1.65.0` (as shown below), which is obviously older than the 2018 Edition.
```bash
downloading https://static.rust-lang.org/dist/2022-11-03/rust-std-1.65.0-x86_64-unknown-linux-gnu.tar.xz
```
It leads to a mismatch with the command `cargo install afl` from the `install-and-test-afl` script (I have addressed this issue by adding `rustup override` command to the script). Could you please confirm if there are any mistakes in this branch/repository, or if the work has been updated without reflecting the changes in the `README`? Thank you.

**Comment by TanjiaJunS** [comment]
how did you add  **rustup override** ? 
which script?
thanks

**Comment by EricLiChH** [comment]
> how did you add **rustup override** ? which script? thanks

Thank you for your reply and sorry for my lateness. I will tell more details on it.
In the script `/scripts/install-and-test-afl`, and in **line-4** ( before the comment `# install afl` ) I added
```bash
rustup override 1.46.0
```
It led to a mismatch between the Rust source code I compiled before (the Rust repo. forked by this project) and thus many of the dependencies would not support the old Rust version.

**Comment by WIZeaz** [comment]
Hi, we have upgraded the version of rust toolchains to `1.65.0` on the `develop` branch. If you want to use an older version of rust toolchains to run RULF, you can checkout to an older commit version `714fc4d84cecde9c0433bc3516e47ab5368cf9bc`. It should be helpful.
